### ISSUE TITLE
Error: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by jduhls** [pilwon/node-neospeech#3]
Building node.js Win32 app with nw.js v0.11.6 (https://github.com/nwjs/nw.js) and hoping to integrate neospeech. Error triggers when I invoke 'require("neospeech")'. Could be node.js version issues? I'm a bit new to node.js

**Comment by jduhls** [comment]
C:\Users\JONATH~1\AppData\Local\Temp\nw5608_18333\node_modules\neospeech\build\Release\neospeech.node
    at Error (native)
    at Module.load (module.js:354:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (C:\Users\JONATH~1\AppData\Local\Temp\nw5608_18333\node_modules\neospeech\lib\index.js:34:15)
    at Module._compile (module.js:454:26)
    at Object.Module._extensions..js (module.js:472:10)
    at Module.load (module.js:354:32)
    at Function.Module._load (module.js:310:12)
